apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    # CONFIGMAP
    user  nginx;
    worker_processes  1;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  ' -  [] "" '
                          '  "" '
                          '"" ""';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        #gzip  on;
    
        include /etc/nginx/conf.d/load-balancer.conf;
    }
  load-balancer.conf: |
    upstream example.com {
      server ad34a08c6400d11e8809d02503122822-1339069138.us-west-2.elb.amazonaws.com weight=1;
      server 35.192.163.132 weight=4;
    }
    server {
      listen 80;
      location / {
        proxy_pass http://example.com;
        proxy_http_version 1.1;
      }
      }
