apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    # CONFIGMAP
    user  nginx;
    worker_processes  1;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  ' -  [] "" '
                          '  "" '
                          '"" ""';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        #gzip  on;
    
        include /etc/nginx/conf.d/load-balancer.conf;
    }
  load-balancer.conf: |
    upstream test.theplatform.com {
      server af8a1f903274111e8ba2202972df1fe7-882212238.us-west-2.elb.amazonaws.com weight=1;
      server 35.230.40.147 weight=4;
    }
    server {
      listen 80;
      location / {
        proxy_pass http://test.theplatform.com;
        proxy_http_version 1.1;
      }
      }
