apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: myapp-routerules
spec:
  destination:
    name: myapp-gke-lb
    namespace: multicloud
    domain: svc.cluster.local
  route:
  - labels:
      stack: prod
    weight: 95
  - labels:
      stack: canary
    weight: 5
